[package]
name = "resource-monitor"
version = "0.1.0"
edition = "2024"

[lib]
name = "app_resource_monitor"

[dependencies]
app_core = { workspace = true }
sysinfo = { workspace = true }
tracing = { workspace = true }
