[package]
name = "usecase"
version = "0.1.0"
edition = "2024"

[dependencies]
foundation = { path = "../foundation" }
domain = { path = "../domain" }
serde_json = { workspace = true }
sysinfo = { workspace = true }
tracing = { workspace = true }
